# Taps
tap argon/mas
tap caskroom/cask
tap caskroom/versions
tap codeclimate/formulae
tap homebrew/boneyard
tap homebrew/core
tap homebrew/versions
tap rcmdnk/file
tap wercker/wercker

# Apps
cask adobe-reader
cask alfred
cask android-studio
cask bartender
cask battle-net
cask dash
cask dropbox
cask flash-player
cask flash
cask google-chrome
cask java
cask lighting
cask macpar-deluxe
cask otto
cask paw
cask razer-synapse
cask shiftit
cask silverlight
cask skype
cask slack
cask smcfancontrol
cask steam
cask virtualbox
cask vlc

brew android-platform-tools
brew cloc
brew codeclimate
brew docbook-xsl
brew docbook
brew docker
brew fish
brew freetype
brew git
brew heroku-toolbelt
brew hub
brew imagemagick
brew jpeg
brew jq
brew libpng
brew libtiff
brew libtool
brew mas
brew mercurial
brew moreutils
brew mysql
brew neo4j
brew ngrok
brew nvm
brew oniguruma
brew openssl
brew pgcli
brew pkg-config
brew postgresql
brew qt
brew readline
brew redis
brew sqlite
brew tree
brew wercker-cli
brew xz



# App Store applications
appstore 443987910 1Password
appstore 836505650 Battery Monitor
appstore 425264550 Blackmagic Disk Speed Test
appstore 411246225 Caffeine
appstore 417602904 CloudApp
appstore 975937182 Fantastical 2
appstore 682658836 GarageBand
appstore 668208984 GifGrabber
appstore 1031444301 Hangouts Plus
appstore 409183694 Keynote
appstore 409203825 Numbers
appstore 409201541 Pages
appstore 568494494 Pocket
appstore 803453959 Slack
appstore 557168941 Tweetbot
appstore 497799835 Xcode
appstore 408981434 iMovie
